# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Fofo's cave
tagline:          
description:      ''
url:              http://padillla.github.io
paginate:         5

author:
  name:           'Rodolfo Padilla'
  twitter:         https://twitter.com/padillla
  facebook:        https://www.facebook.com/rodolfo.padillaruiz
  repository:      padillla/padillla.github.io

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/padillla/padillla.github.io

gems:    
  - github-pages
  - jekyll-coffeescript
  - jekyll-paginate
  - jekyll-redirect-from