# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Fofo's cave
tagline:          
description:      ''
url:              http://padillla.github.io
paginate:         5

author:
  name:           'Rodolfo Padilla'
  twitter:         https://twitter.com/padillla
  facebook:        https://www.facebook.com/rodolfo.padillaruiz

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/padillla/padillla.github.io
