# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Fofo's thoughts cave
tagline:          
description:      ''
url:              http://padillla.github.io
paginate:         5

author:
  name:           'Rodolfo Padilla'
  twitter:         https://twitter.com/padillla
  facebook:        https://www.facebook.com/rodolfo.padillaruiz
  linkedIn:        https://www.linkedin.com/in/r-padilla-ruiz/

# Custom vars
version:          1.0.0


repository: padillla/padillla.github.io


gems:    
  - github-pages
  - jekyll-coffeescript
  - jekyll-paginate
  - jekyll-redirect-from